### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by ShanaScogin** [ShanaScogin/BayesPostEst#11]
Add unit tests in testthat

**Comment by ShanaScogin** [comment]
@jkarreth do you have some examples of how to use rocprc? I started a test file, but I want to understand the function first. (I also see we have to generalize the sims to more than just a stan object for rocprc)
(edit: some examples for mcmcLogitFD or mcmcProbitFD (which are now combined into one) would also be great, if they exist. - here's the current test for mcmcFD: https://github.com/ShanaScogin/BayesPostEst/blob/master/tests/testthat/test_mcmcFD.R)

**Comment by jkarreth** [comment]
@ShanaScogin definitely! Quick example below. Does this help?

```
library("rstanarm")
d <- carData::Cowles
d$female <- (as.numeric(d$sex) - 2) * (-1)
d$volunteer <- as.numeric(d$volunteer) - 1

m <- stan_glm(volunteer ~ female + neuroticism + extraversion, 
              data = d,
              family = binomial(link = "logit"))

# Using mcmcRocPrc

# with median draws

fit_sum <- mcmcRocPrc(sims = m,
                  modelframe = model.frame(m),
                  fullsims = FALSE)

fit_sum$area_under_roc
plot(x = fit_sum$roc_dat$x, y = fit_sum$roc_dat$y, type = "l", main = "ROC")
abline(a = 0, b = 1)

fit_sum$area_under_prc
plot(x = fit_sum$prc_dat$x, y = fit_sum$prc_dat$y, type = "l", main = "PRC")

# full draws

fit_full <- mcmcRocPrc(sims = m,
                  modelframe = model.frame(m),
                  fullsims = TRUE)

# works but this is slooooow!

# area under roc:
area_under_roc <- unlist(lapply(fit_full, '[[', 1))
area_under_prc <- unlist(lapply(fit_full, '[[', 2))
```

**Comment by ShanaScogin** [comment]
Perfect! I'll get that up!

**Comment by ShanaScogin** [comment]
Tests that still need a lot of work:

- [x] test_mcmcRocPrc
edit: struck out the graph functions

Tests that could have a probit check built in (but otherwise pretty well formed):

- [x] test_mcmcObsProb
- [x] test_mcmcAveProb

I'm going to work on simulating some data for the mcmcRocPrc test instead of relying on another package to reduce dependencies first.

**Comment by jkarreth** [comment]
OK!

@ShanaScogin Please let me know if/how I can help with the tests that still need a lot of work.

On mcmcRocPrc - sounds good; any simulated data for a logit model should do, even with only one predictor.

**Comment by jkarreth** [comment]
Re: mcmcPPplot, since we decided that this function is not being included in the package at this time, can we make things easier by deleting it from the repo right now to avoid test errors?

**Comment by ShanaScogin** [comment]
Sounds good - I can just add mcmcPPplot to the build ignore file for now. Convention is to have a test file per function as far as I understand, but I've combined fd and fd plot function testing. I can split them if nec. dfBarTable is a bit buggy for some reason - perhaps we should cut that out, too?

**Comment by jkarreth** [comment]
Yup! If dfBarTable in any way proves to be a bottleneck (and it sounds like it does), please take it out at least for now. Thanks!

**Comment by ShanaScogin** [comment]
Alright - think I'm going to close this now. The tests are up - we could always add more to them to check other functionality as we continue, but they're up and running with simple examples right now. Thanks all!
