### ISSUE TITLE
Combine mcmcprobitfd and mcmclogitfd into mcmcFD

### ISSUE THREAD

**Issue by ShanaScogin** [ShanaScogin/BayesPostEst#13]
I started this last night, but need to delete mcmcProbitFD and mcmcLogitFD and make sure mcmcFD is generalized - wanted to check with you first, though @jkarreth

**Comment by jkarreth** [comment]
sounds good, please go ahead

**Comment by ShanaScogin** [comment]
I am going to go ahead and close this - the function still needs to be tested thoroughly, but I combined both into mcmcFD
