### ISSUE TITLE
standardize how CI for posteriors is specified

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#14]
Currently:

- `lower = 0.05, upper = 0.95` in `mcmcAveProb` and `mcmcObsProb`
- `ci = c(0.05, 0.95)` in mcmcFD
- `ci = 0.95` in mcmcTab

I like `ci = c(0.05, 0.95)` best - explicit, yet short. 

This should be implemented in all functions that require specifying the CI: 
- [x] mcmcAveProb
- [x] mcmcObsProb
- [x] mcmcFD
- [x] mcmcTab

**Comment by ShanaScogin** [comment]
Great - I've completed these. Have tested mcmcObsProb, but not others

**Comment by ShanaScogin** [comment]
The default for mcmcTab is currently c(0.025, 0.975) and the others are c(0.05, 0.95). Do we want to standardize?

**Comment by jkarreth** [comment]
Yes, let's use `c(0.025, 0.975)` for 95% CI throughout.

**Comment by ShanaScogin** [comment]
this is done.
