### ISSUE TITLE
add plot functions? 

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#17]
Shana's #16 made me wonder: it was inefficient of me to duplicate the computation and plotting of FDs and PPs in the plotting functions.

Instead, it seems like it would be better to generate two plotting functions. Each takes the output from `mcmcAveProb`/`mcmcObsProb` and `mcmcFD`, respectively and generates the desired plots. 

Thoughts?

**Comment by ShanaScogin** [comment]
Oohh this makes sense. So perhaps it would be a plot() wrapper like Xu's gysnth package? (You can just throw plot() around the gysnth object and specify the type of plot - it's really nice.) I think that could work. I can work on that tomorrow after I work on mcmcObsProb tonight, unless you have any new ideas by then?

**Comment by jkarreth** [comment]
That would be one way, though it would require us to define a new object class (like a gsynth object), right?

So I was thinking an easier and quicker way (for now!) would be just a simplified version of the current function that still takes as input the output created from mcmcAvePP, for instance, like so:

```
predprob <- mcmcAvePP(...)
mcmcPPplot(input = predprob, ...)
```

Would you be OK with that?

**Comment by ShanaScogin** [comment]
Ah sure - Ya that makes sense and sounds good. I'll play with it tomorrow. (Though, I am probably going to define these as a new object classes for the print functions anyway tonight, so it might be not that bad. I'll play with it tomorrow and kick it over to you to see what you think?)

**Comment by jkarreth** [comment]
Great! 

I'm indifferent re: object classes. For teaching & programming purposes, tibbles / dataframes are sufficient (for me), but do whichever you think works best. I'd just want to make sure that the output from `mcmcAveProb`, `mcmcObsProb`, `mcmcFD` always reduces to a dataframe (if that makes sense)

**Comment by ShanaScogin** [comment]
Ahh hm - that makes total sense. Might not be able to do the object then? Would having to specify object$dataframe be too much? I wonder if I could do something with summary() so it spits out a dataframe when one runs it, but one can do summary() to spit out nice stuff. I haven't made something to work with summary() yet so I will mess around with it and let you know?

**Comment by jkarreth** [comment]
This brings me to the boundaries of my R knowledge ☺️

I like the summary idea. 

For background, my original intention for these functions was to generate data frames to then plot (or summarize) with separate code. I hadn't thought about printing them, since they are objects to be further processed. 

But I'll defer to you on this as long as the functions do create data frames that can be used further.

**Comment by ShanaScogin** [comment]
Ya definitely - it's your package, so you know the needed functionality! I was just thinking in terms of user friendliness - when I was plotting with the observed value function for the homework, I was getting funky results - turns out I was putting in the wrong explanatory variable (which is currently a model matrix column number). If it had spit out something like, 'these results for this variable (or something)' it might have been more obvious, but it was just a thought. (This also might be precluded here since the user will now have easily accessible, nice documentation in the package, or there might be another solution all together.) I'm just spitballing - when I start to work on it, a solution might present itself. @mlq38 and @snpwill also might have thoughts since they've been troubleshooting the function(s) with us lovely folks all week.

**Comment by jkarreth** [comment]
These are good points!

You're right that proper column order (and subsequently specification of `x_col`) is the most frequent error I've seen in working with users. Can't think of a clear way to prevent this though, since column *names* from MCMC output (from JAGS) depend on variable names used in the model.

I like your suggestion that documentation should fix this (for now) by including a reminder that the order of columns in mcmc_out and model_matrix must be the same. If we can think of a better solution later, we can implement it then.

**Comment by jkarreth** [comment]
Decided to drop plotting functions (#6 ) and instead show plotting in vignette (#9).
