### ISSUE TITLE
add function to plot marginal effect after interaction in linear model

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#21]

**Comment by jkarreth** [comment]
Let's build on @jayrobwilliams mcmcme for this function.

**Comment by jayrobwilliams** [comment]
What do we want to call this? Right now I'm leaning towards `mcmcMargEff` but open to any other suggestions. @ShanaScogin?

**Comment by jayrobwilliams** [comment]
to do:
- [x] example data and model results creation files similar to @andybega's for `jags_logit` and `jags_probit`
- [x] add hpdi option like in `mcmcReg`
- [x] rewrite documentation to fit with package style

**Comment by jayrobwilliams** [comment]
Completed in 8ca95c1448b6a5b380d6ef32e84b0cff255ed383
