### ISSUE TITLE
add full_sims option to mcmcAveProb and mcmcObsProb

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#22]
like in mcmcFD, so something like this for mcmcAveProb:

```
if(full_sims == FALSE){
    return(pp_dat) # pp_dat was created by summarizing longFrame
  }
  
  if(full_sims == TRUE){
    names(longFrame) <- c("Iteration", "x", "pp")
    return(longFrame) 
  }
```

and for mcmcObsProb it should be:

```
if(full_sims == FALSE){
    return(pp_dat) # pp_dat was created by summarizing longFrame
  }
  
  if(full_sims == TRUE){
    longFrame <- reshape2::melt(pp_mat, id.vars = Var2)
    names(longFrame) <- c("Iteration", "x", "pp")
    return(longFrame) 
  }
```

Eventually we should standardize the names of the arguments & intermediate objects and make the two functions (mcmcAveProb and mcmcObsProb) a bit more similar, but the general idea should work. (Just maybe add a warning that the longer `xrange` becomes the larger pp_mat will be.)

**Comment by jkarreth** [comment]
to keep track:
- [x] added to mcmcAveProb
- [x] added to mcmcObsProb

**Comment by ShanaScogin** [comment]
I haven't standardized these functions fully (though I do think I might have standardized the argument names), but I did add your code to return full simulations. Seems to be working.

**Comment by jkarreth** [comment]
This looks good to me now; should we close this issue?

**Comment by ShanaScogin** [comment]
Sure thing. Will close.
