### ISSUE TITLE
mcmcFDplot: error using gather

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#26]
```
library("rstanarm")
d <- carData::Cowles
d$female <- (as.numeric(d$sex) - 2) * (-1)
d$volunteer <- as.numeric(d$volunteer) - 1

m <- stan_glm(volunteer ~ female + neuroticism + extraversion, 
              data = d,
              family = binomial(link = "logit"))

fd_full <- mcmcFD(modelmatrix = model.matrix(m),
                 mcmcout = as.matrix(m), 
                 link = "logit",
                 ci = c(0.025, 0.975),
                 percentiles = c(0.25, 0.75),
                 fullsims = TRUE)

mcmcFDplot(fdfull = fd_full)
```

Error:  Must supply a symbol or a string as argument

This creates the error:

```
foo <- tidyr::gather(as.data.frame(fd_full), 
             key = .data$variable, 
             value = .data$fd)
```

whereas not specifying arguments for key and value works as intended:

```
foo <- tidyr::gather(as.data.frame(fd_full))
```

Can the .data$variable and .data$fd be removed without breaking any of the testing functions?

**Comment by ShanaScogin** [comment]
-_- I honestly have no idea. Just learning how to tidyverse in a package. I think we should get the function working and I can troubleshoot the cmd check notes later. It'd be great to get a test for this going too so I'd be more able to check that.

**Comment by jkarreth** [comment]
Sounds good! Then I would recommend replacing lines 17-20:

```
  # convert fdfull to long data frame
  fd_dat <- tidyr::gather(as.data.frame(fdfull), 
                 key = .data$variable, 
                 value = .data$fd) ## check this
```

with:

```
  # convert fdfull to long data frame
  fd_dat <- tidyr::gather(as.data.frame(fd_full))
```

**Comment by ShanaScogin** [comment]
fixed this. now i'm getting an error with the .data I had before, but it's more general than this function. Not sure what's up since this was solved two days ago, but I'll troubleshoot this after we have all the functions up and running. 

checking dependencies in R code ... WARNING
  '::' or ':::' import not declared from: ‘.data’
