### ISSUE TITLE
mcmcTab: add warning when ROPE is specified

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#27]
mcmcTab should print a message above or below the table when ROPE is not NULL. The warning should read something like:

"This table contains an estimate for parameter values outside of the region of practical equivalence (ROPE). For this quantity to be meaningful, all parameters must be on the same scale (e.g. standardized coefficients or first differences)."

**Comment by ShanaScogin** [comment]
I've added a draft of this - Do you have a good example of code using ROPE I could test this out on?

**Comment by jkarreth** [comment]
Great, thanks! Does the example in the vignette work? 

The way you simulate data and fit the model in mcmcTab.R should already do the trick. The warning looks good to me! I might just misunderstand the question, though - let me know what I can provide.

**Comment by ShanaScogin** [comment]
Perfect. I've just added a message, so it prints out red when it runs, but it isn't in the actual table. It's running fine. If that sounds good, this can be closed.

**Comment by jkarreth** [comment]
The message looks great, thank you for adding that.
