### ISSUE TITLE
mcmcRocPrc: summarize x & y

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#32]
Instead of the final output containing the full posterior distribution for x and y for the ROC and PRC, summarize these two with only median and CI.

**Comment by jkarreth** [comment]
low priority for now

**Comment by jkarreth** [comment]
package can go to CRAN without this change.

**Comment by andybega** [comment]
Should this be a job for `summary` and/or `print` methods?

**Comment by jkarreth** [comment]
I was originally thinking analogous to mcmcAveProb when `fullsims = FALSE`, but using `summary` or `print` instead is a good idea.

**Comment by andybega** [comment]
Hey, I just submitted a pull request for the `mcmcRocPrc()` speed improvements. I'll tackle this next.

**Comment by andybega** [comment]
Hello, so with some delay, I now managed to get a first version of this going. Right now it looks like this:

``` r

library(BayesPostEst)
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2

data("jags_logit")

# basic case without full sims
with_curves <- mcmcRocPrc(jags_logit,
                          yname = "Y",
                          xnames = c("X1", "X2"),
                          curves = TRUE,
                          fullsims = FALSE)

with_curves
#> mcmcRocPrc object
#> curves: TRUE; fullsims: FALSE
#> AUC-ROC: 0.627
#> AUC-PR:  0.621
plot(with_curves)
```

![](https://i.imgur.com/LSjMkmu.png)

``` r

# with full sims, it'll sample a few curves (n = 40 by default) to plot, 
# and add a averaged curve as well
full_with_curves <- mcmcRocPrc(jags_logit,
                               yname = "Y",
                               xnames = c("X1", "X2"),
                               curves = TRUE,
                               fullsims = TRUE)

full_with_curves
#> mcmcRocPrc object
#> curves: TRUE; fullsims: TRUE
#> AUC-ROC: 0.624 [80%: 0.619 - 0.627]
#> AUC-PR:  0.618 [80%: 0.613 - 0.620]
plot(full_with_curves, alpha = 0.2)
```

![](https://i.imgur.com/hPOclta.png)

``` r

# error if the original call was without curve data
no_curves <- mcmcRocPrc(jags_logit,
                        yname = "Y",
                        xnames = c("X1", "X2"),
                        curves = FALSE,
                        fullsims = FALSE)

plot(no_curves)
#> Error in plot.mcmcRocPrc(no_curves): Use mcmcRocPrc(..., curves = TRUE) to generate data for plots
```

<sup>Created on 2020-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The alpha values don't seem to work super well with base plot, and maybe there would also be a point in adding a ggplot2::autoplot() method. Otherwise, does this seem ready for a pull request?

BTW, I added some basic tests for the methods, but R check fails because of a vignette building issue that I think you guys are aware of.

**Comment by andybega** [comment]
One question--and sorry for being out of the loop, I see that you guys (@jayrobwilliams?) back in December added `mcmcRocPrcGen()` back in, what's the reason for that? Backward compatibility?

**Comment by jayrobwilliams** [comment]
Sort of. `mcmcRocPrc()` only works with JAGS objects, so the purpose of `mcmcRocPrcGen()` is to maintain a way to generate ROC and PR curves from all types of model objects. Taking a look at your code, I *think* I can adapt it use our extraction methods that we use in `mcmcTab()` and `mcmcReg()` to handle all types of model objects. The tradeoff is we'll have to ask the user for a bit more information in the function call, but I think that's worth it. @ShanaScogin would you approve a pull request into a feature branch and then I can work on it there?

Also, @andybega the print and plot methods look great, I think I can handle adding `ggplot2` support to the plot method if @ShanaScogin is ok with a PR to a feature branch.

**Comment by andybega** [comment]
What about handling this sort of stuff via methods and classes? E.g. make mcmcRocPr a generic, the current version becomes a method for JAGs objects, the gen method becomes a mcmcRocPr.default or something. 

BTW, If I remember right, I changed the internals to reimplement what ROCR was used for before, as it is quite slow when using fullsims = TRUE.

**Comment by andybega** [comment]
On my phone and don’t remember exactly the details, but could then maybe basically be so that the gen version that requires the model matrix and co becomes the default method, and the .jags method turns into a thin wrapper that extracts the model matrix and then calls the default method with it. In any case, the point would be that the user would not have to chose between two functions, it should work the same for them whether they pass a model matrix or jags logit/probit object.

**Comment by andybega** [comment]
Hey, I cleaned up what I had so far in `mcmcRegPrc()` + methods since it addresses the original issue. 

> Taking a look at your code, I think I can adapt it use our extraction methods that we use in mcmcTab() and mcmcReg() to handle all types of model objects. The tradeoff is we'll have to ask the user for a bit more information in the function call, but I think that's worth it.

I have a bit of time to contribute more, @jayrobwilliams is it ok with you if I take this on?

**Comment by jayrobwilliams** [comment]
Sure! I think the goal should be that no matter what type of object a user passes to `mcmcRocPrc()`, the required arguments are the same e.g., right now `mcmcRocPrc()` extracts the link function from the model via regex but `mcmcRocPrcGen()` requires the user to specify it as a string. If you can figure out a way to grep the link function out of every type of model object, then we should stick with that, but if not we should require the user to specify it via an argument.

**Comment by andybega** [comment]
Alright. I guess this generalization is already covered by #5, I sketched out a plan there and will try to see if this automatic link extraction, etc. can also be done for the other types of objects. 

If I manage to come up with any general solutions that touch on #43 I'll try to make a mention there as well.

**Comment by andybega** [comment]
BTW, is this issue good for closing?

**Comment by jkarreth** [comment]
Yes, with all the upgrades to [mcmcRocPrc.R](https://github.com/ShanaScogin/BayesPostEst/blob/develop/R/mcmcRocPrc.R) this is definitely addressed. Thank you for taking care of these!
