### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#4]
Use `Cowles` from R's pre-loaded datasets?

```
> summary(glm(volunteer ~ sex + neuroticism + extraversion, data = Cowles, family = binomial(link = "logit")))

Call:
glm(formula = volunteer ~ sex + neuroticism + extraversion, family = binomial(link = "logit"), 
    data = Cowles)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.3977  -1.0454  -0.9084   1.2601   1.6849  

Coefficients:
              Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -1.116496   0.249057  -4.483 7.36e-06 ***
sexmale      -0.235161   0.111185  -2.115   0.0344 *  
neuroticism   0.006362   0.011357   0.560   0.5754    
extraversion  0.066325   0.014260   4.651 3.30e-06 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1933.5  on 1420  degrees of freedom
Residual deviance: 1906.1  on 1417  degrees of freedom
AIC: 1914.1

Number of Fisher Scoring iterations: 4
```

**Comment by jkarreth** [comment]
I made an error: `Cowles` is part of the {carData} package. Can we reuse it and include it in this package?

Is there a better example dataset in {[datasets](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html)}?

The example dataset should have:

- [ ] a binary outcome variable
- [ ] at least one binary predictor
- [ ] at least one continuous predictor

**Comment by snpwill** [comment]
We could use the Titanic data from the datasets package. This has a binary outcome (survival) and a binary indicator (Gender). However, the closest thing to a continuous predictor would be the class variable which only has four values.

**Comment by snpwill** [comment]
Actually nevermind. The Titanic data seems to be frequency tables.

**Comment by mlq38** [comment]
I looked at all datasets in {datasets}, but could not find any thing that matches the criteria. attitude data has a continuous outcome (rating) and other 6 continuous variables and maybe we can recode the outcome variable and one of the IVs to get two binary indicators.

**Comment by jkarreth** [comment]
Thank you for looking into these! I think `carData::Cowles` can work well. Could you check whether there are any licensing restrictions to re-use these data in a different package? 

When we use it, we would also need to convert the variables to all numeric (so it makes processing for JAGS/BUGS/Stan easier), like so:

```
d <- carData::Cowles
d$female <- (as.numeric(d$sex) - 2) * (-1)
d$volunteer <- as.numeric(d$volunteer) - 1
```

**Comment by jkarreth** [comment]
Example data will only show up in the vignette, and we can load it from carData there. All examples in the package work with simulated data.
