### ISSUE TITLE
add coefficient plot function

### ISSUE THREAD

**Issue by jayrobwilliams** [ShanaScogin/BayesPostEst#41]
add a function to create a coefficient plot from Bayesian model objects, allowing users to supply the parameters they wish to include.

**Comment by jkarreth** [comment]
This is great! Want to name it `mcmcCoefPlot` or similar for consistency with `mcmcFDplot`?

**Comment by jayrobwilliams** [comment]
Initial code completed in e6d610212e71041b872e0ee795670e44d2e2aaea. Will leave in a feature branch for further testing/enhancement until I assign this to a milestone later.

**Comment by jayrobwilliams** [comment]
Completed in cb684f30e14606b420aaf6098c3fd35eda1c4b5b
