### ISSUE TITLE
Validate mcmcTab ROPE input

### ISSUE THREAD

**Issue by andybega** [ShanaScogin/BayesPostEst#44]
The current code seems to work no matter what the ROPE input is:

```r
mcmcTab(fit, ROPE = "a")
```

produces:

```
  Variable Median    SD  Lower Upper PrOutROPE
1     b[1]  0.108 0.090 -0.066 0.285         1
2     b[2]  0.527 0.166  0.197 0.837         1
3     b[3]  0.636 0.161  0.328 0.948         1
```

**Comment by jkarreth** [comment]
Thank you for catching this! I'll look into it - perhaps as straightforward as adding a warning if the input to ROPE is not a vector of 2 numeric values.

**Comment by andybega** [comment]
Hello, this is fixed in one of the commits (https://github.com/andybega/BayesPostEst/commit/1a7b54d5e72fc31caef699e2b6d8170e0dd9acac) in my pull request (#46).

**Comment by jkarreth** [comment]
Fantastic! Thank you. @ShanaScogin , can you close this once Andy's pull request (#46 ) is merged with master?

**Comment by ShanaScogin** [comment]
Done and done!
