### ISSUE TITLE
adjust "percentage point" term in mcmcFDplot

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#55]
`mcmcFDplot` mentions "percentage point change" in the x-axis label, but the plotted quantity is change on the 0-1 probability scale (e.g. 0.2 would move from Pr(y = 1) from 0.1 to 0.3, but technically that's equivalent to a 20 percentage point change).

Solution: either

- [ ] change the label, or

- [ ] add a line under `fd_dat <- tidyr::gather ...` that multiplies the changes by 100: `fd_dat$value <- fd_dat$value * 100`

**Comment by jayrobwilliams** [comment]
Working on this now. I think percentage point change is more intuitive than 0-1, so my vote would be that. However, does that mean we should also have users specify the ROPE from 0-100 instead of 0-1 now? Easy to change, but wanted to check.

**Comment by jkarreth** [comment]
Agreed @jayrobwilliams - let's change ROPE to 0-100 as well. If you can tackle that, great - if not, let me know and I'll update.

**Comment by jayrobwilliams** [comment]
Sounds good. be01e4865 changes percentage point change and ROPE to 0-100. It also creates and `mcmcFD` class and implements `print()` and `plot()` methods.
