### ISSUE TITLE
add more options such as Std. dev. to mcmcReg, beyond CI

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#57]
add:

- [x] standard deviation (as in `mcmcTab`)
- [x] p-direction / probability that estimate is in same direction as mean (as in `mcmcTab`)

**Comment by jayrobwilliams** [comment]
Standard deviations added in 8de200b0771ef9c54ab9d2c8dc4fd42ac7c7617c. Probability that estimate is in the same direction as the mean will probably take some regex magic to do since `texreg` only supports SEs and CIs under estimates.

**Comment by jayrobwilliams** [comment]
Probability of direction was easier than I expected, that's in db88052. I'll close this issue once I've written new tests for both functionalities.

**Comment by jayrobwilliams** [comment]
Tests written in 4d6ccf5. Now I just need to get my hands on a BUGS model object and `mcmcReg` can have prefect testing coverage!

**Comment by jkarreth** [comment]
Super!

@ShanaScogin, please add this to the next deploy to CRAN - seems like the updated version is currently in `feature/mcmcReg` but should be moved to the `developer` or `master` branch? (Might also be my lack of understanding of Github.)

**Comment by jayrobwilliams** [comment]
@jkarreth as collaborators on this repo, we can both merge. I've just merged the updates from `feature/mcmcReg` into `develop` in 56468bc.
