### ISSUE TITLE
fix help file for mcmcCoefPlot

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#59]
currently refers to `coefplot`, replace that reference with `mcmcCoefPlot`. 

Trivial, but I can't get to it tonight

**Comment by jkarreth** [comment]
This part at the bottom of the example:

```
## generating coefficient plot with all non-auxiliary parameters
coefplot(fit)
#> Error in coefplot(fit): could not find function "coefplot"
# }
```

**Comment by ShanaScogin** [comment]
I fixed this - was it just the one in the example? If so, feel free to close the issue - if not let me know! Thanks for catching that!

**Comment by jkarreth** [comment]
Yup, I only came across this in the help file. Since you already addressed this, I'll leave it alone. Can't find this in the master or develop branch though - but as soon as you've implemented it for the next version to go to CRAN, @ShanaScogin,  please feel free to close. Thanks! Johannes

**Comment by ShanaScogin** [comment]
Great - I had fixed it in the R file but not run devtools::document() yet, but have now. We should be good to go!
