### ISSUE TITLE
Update documentation for FD plotting

### ISSUE THREAD

**Issue by ShanaScogin** [ShanaScogin/BayesPostEst#62]
Update documentation for new FD plot functionality. Include note on depreciating mcmcFDplot() in examples

**Comment by jayrobwilliams** [comment]
Updated documentation and deprecated `mcmcFDplot()` in 7774e62. It doesn't have an explicit note in the documentation, but is marked as deprecated and will throw a warning. Take a look at the and let me know if this is good to close out.

**Comment by ShanaScogin** [comment]
Awesome - looks great - I think all that's left is the vignettes and readme

**Comment by jayrobwilliams** [comment]
I've already done the vignette, but I'll do the README now.

**Comment by ShanaScogin** [comment]
Awesome - Do you want to do BayesPostEst.R as well? I _think_ it might be good to put a note about the depreciation there as well rather than deleting it from the list completely yet, but I think either way would probably be fine.

**Comment by jayrobwilliams** [comment]
Added to `BayesPostEst.R` and added a note about deprecation in NEWS in f6995d3.
