### ISSUE TITLE
R check errors for documentation examples

### ISSUE THREAD

**Issue by andybega** [ShanaScogin/BayesPostEst#64]
A couple of the examples in documentation files are not working. The examples are wrapped in `\donttest{}`, so I guess they don't show up in the CRAN R checks, but locally for me they do show up as a R check ERRORs (with `--run-donttest`). 

A couple were in the data documentation files, but there are others as well.

In the data documentation try to do `as.list(data)`, where `data` is not defined. R thus falls back to trying to coerce the function `data()` to a list, which works, but invariable causes an error down the line when trying to fit a model. 

```
Error in jags.model(model.file, data = data, inits = init.values, n.chains = n.chains,  : 
    unnamed variables in data list
```

The problem are small typos in the example code. E.g. instead of:

```r
#' data("sim_data_interactive")
#' 
#' ## formatting the data for jags
#' datjags <- as.list(data)
```

it should be 

```r
#' data("sim_data_interactive")
#' 
#' ## formatting the data for jags
#' datjags <- as.list(sim_data_interactive)
```

I'll try to work through these until R check passes without examples errors.

**Comment by andybega** [comment]
Wups

![Screen Shot 2020-06-16 at 15 21 10](https://user-images.githubusercontent.com/1353756/84773403-09805b80-afe5-11ea-8e0c-dc2c6660c632.png)

EDIT: ok, actually most of these do create `data` objects.

**Comment by ShanaScogin** [comment]
Hi @andybega - This is great - Did your pull request address these, or are there more to look out for?

**Comment by andybega** [comment]
Hi, this should have been all of them, and I checked on my laptop with devtools check in addition to Travis. Fingers crossed.

**Comment by ShanaScogin** [comment]
Awesome! I'll keep my eye out too, then!
