### ISSUE TITLE
Figures in website

### ISSUE THREAD

**Issue by ShanaScogin** [ShanaScogin/BayesPostEst#70]
Get figures up on the website

**Comment by ShanaScogin** [comment]
I'm working on getting the images up in the readme first before I tackle the website. RMD readme file is working with the badges commented out in 2a67a82fe41789156ca0b466c14ef9d9e0d1c96b. With the badges in, I get the following error upon knitting.

```
pandoc: Could not fetch http://www.r-pkg.org/badges/version/BayesPostEst
TlsExceptionHostPort (HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,HandshakeFailure)])")) "www.r-pkg.org" 80
Error: pandoc document conversion failed with error 67
Execution halted
```

**Comment by jayrobwilliams** [comment]
Is this locally? What pandoc version are you running? I can knit `README.Rmd` without issue and I've got pandoc 2.10.

**Comment by ShanaScogin** [comment]
Awesome - you're right. I'm not sure what version I was on, but an update fixed it. I'm going to see what's up with Travis in issue #74 and then get back to this.

**Comment by jayrobwilliams** [comment]
Figures work in the [vignette](https://shanascogin.github.io/BayesPostEst/articles/getting_started.html) but not in the [README](https://shanascogin.github.io/BayesPostEst/). They also work in the reference pages for function documentation. That might be a starting point.

**Comment by ShanaScogin** [comment]
They do currently work in the readme - at least on github. I added an rmd file a while back that fixed that. We were set up for travis to be pushing for the website, so there might be something in that that's not rendering the images. Will update soon.

**Comment by jayrobwilliams** [comment]
Fixed in 886bc14. Found out in https://github.com/r-lib/pkgdown/issues/280 that only the contents of`vignettes` and `man/figures` are copied by pkgdown. I added a `fig.path` to `README.Rmd` and that *should* fix it given that I did the same on the pkgdown site for my package and it's working. Let me know if this works the next time you merge develop into main, @ShanaScogin

**Comment by ShanaScogin** [comment]
Heck ya!! You're the best! I'll set aside a few hours this weekend to do this and some other package logistical stuff this weekend and let you know. Super awesome!

**Comment by jayrobwilliams** [comment]
As an added bonus, this should fix images in the README on CRAN...

**Comment by ShanaScogin** [comment]
Seems to be fine - the check fails are gone with pull #83
