### ISSUE TITLE
Installing V8 package fails on Travis-CI

### ISSUE THREAD

**Issue by andybega** [ShanaScogin/BayesPostEst#73]
This is the error showing up on both the master and develop branches, and the pull request I submitted.

```
* installing *source* package ‘V8’ ...
1179** package ‘V8’ successfully unpacked and MD5 sums checked
1180** using staged installation
1181Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
1182Using PKG_LIBS=-lv8 -lv8_libplatform
1183-----------------------------[ ANTICONF ]-------------------------------
1184Configuration failed to find the libv8 engine library. Try installing:
1185 * deb: libv8-dev or libnode-dev (Debian / Ubuntu)
1186 * rpm: v8-devel (Fedora, EPEL)
1187 * brew: v8 (OSX)
1188 * csw: libv8_dev (Solaris)
1189To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
1190R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
1191---------------------------[ ERROR MESSAGE ]----------------------------
1192<stdin>:1:16: fatal error: v8.h: No such file or directory
1193compilation terminated.
1194------------------------------------------------------------------------
1195ERROR: configuration failed for package ‘V8’
```

**Comment by ShanaScogin** [comment]
Unless I'm missing something, it's passing now - I wonder if it isn't a Travis thing. Master/main failed a few months ago as well though it had passed with the same commit previously. I'll keep an eye out for it.

**Comment by andybega** [comment]
Yeah, maybe. This V8 thing is new. There were also two other minor issues that caused build warnings (inits values in one of the doc example calls to run.jags, and documentation for the BUGS example object that Johannes added). 

I guess if you merge `develop` into `master` the latter should work again as well.

**Comment by ShanaScogin** [comment]
I actually took out the BUGS example and reverted master/main to the version that passed and it still failed, but ya point taken. I might go ahead and merge this one just to see. Fingers crossed.

I had made a branch with the BUGS example object with the intention of finding if there was something throwing Travis off there as well, but I might go ahead and delete that if you've put everything needed into the recent pull.

**Comment by andybega** [comment]
> I actually took out the BUGS example and reverted master/main to the version that passed and it still failed, but ya point taken.

I added Johannes' commit with the BUGS example in (with `git cherry-pick`) to the stuff that is now in `develop`, so it should work...fingers crossed.

**Comment by ShanaScogin** [comment]
~~Green checks at the moment!~~ Had a nondescript error with commit 11dfd0f8d760f2bd12f999f0a044b190b662dd3f, but a commit later (minor conflict fix - nothing to do with Travis) and it's fine. I'll leave it up to you if you want to close the issue - I imagine we'll probably see something funky like this again in the future, but I'm not totally sure what to do about it.

edit: It failed again tonight and isn't pushing the gh-pages. I opened #74 to look into the latter. Maybe I'll find something about this, too.

**Comment by ShanaScogin** [comment]
I'm going to go ahead and close this since we're going to have to move away from travis (see issue #76 for updates on that)
