### ISSUE TITLE
Cran R Version Issue

### ISSUE THREAD

**Issue by ShanaScogin** [ShanaScogin/BayesPostEst#80]
email from cran: 

> Dear maintainer,
> your package still fails under R < 4.0.0.
> <https://cran.r-project.org/web/checks/check_results_BayesPostEst.html>
> 
> Please really fix this issues or declare
> Depends: R (>= 4.0.0)
> 
> Please fix and resubmit.

**Comment by jkarreth** [comment]
I'd be ok with declaring `Depends: R (>= 4.0.0)`!

**Comment by ShanaScogin** [comment]
Nothing else has been emailed so perhaps I'm going to close this for now. I'm wondering if there was something in our imports that fixed it? I'll keep my eye on it.
