### ISSUE TITLE
Cran issues to resolve

### ISSUE THREAD

**Issue by ShanaScogin** [ShanaScogin/BayesPostEst#82]
Email is below: 

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_BayesPostEst.html>.
> 
> Please correct before 2021-10-05 to safely retain your package on CRAN.
> 
> Do remember to look at the 'Additional issues'.
> 
> The CRAN Team

Seems to be an rjags and/or r2jags issue

> Warning: namespace ‘rjags’ is not available and has been replaced
> See https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/BayesPostEst-00install.html for details.

I will work on this this weekend to get ahead of the 10/5 drop off date.

**Comment by ShanaScogin** [comment]
I couldn't find the problems in time (and the errors have changed) and it was thrown off cran. Will work on this this weekend. Still getting github check error from some website stuff (that was ok in dev) from Rob's fix, so I'll check both of those out, fix, and resubmit.

**Comment by jkarreth** [comment]
Argh, I saw this too late, my apologies. Let me know if I can help. 

If it's at all useful, should we remove/replace the examples in data-raw that rely on R2jags/rjags? Seems like those have created dependency issues in the past?

**Comment by jayrobwilliams** [comment]
I'd be fine removing any examples/tests that use R2jags. Do we have any sense what the most common R packager for JAGS is these days? It could make sense to just stick with that and make all of the others fully optional.

**Comment by jkarreth** [comment]
Based on download counts, it would be rjags, so we could replace all uses of R2jags with rjags.

That said, all of the jags interfaces (rjags, R2jags, runjags) seem to be updated fairly regularly. 

@ShanaScogin , if/when you get a chance to identify the errors, please feel free to get me/us to contribute fixing them especially if this is dependency related...

**Comment by ShanaScogin** [comment]
@jayrobwilliams did all the heavy lifting. I edited a few urls and submitted. Will update when accepted.

**Comment by ShanaScogin** [comment]
Thrown back with some fails. I'm cleaning up the errors found with cmd check with the suggested environ variable R_CHECK_DEPENDS_ONLY_

`devtools::check(pkg = ".", env_vars = c(R_CHECK_DEPENDS_ONLY_="true"))`

**Comment by ShanaScogin** [comment]
Added a lot of interactive() conditionals to not run the code in CRAN checks (need to make sure this doesn't mess up some testing, but we have an issue open for that so I think it's fine for now) in 9c87c7a. The check with the env var passes on my end, yet CRAN is still having issues. Per their email:

> * checking tests ... [4s] ERROR
>    Running 'testthat.R' [3s]
> Running the tests in 'tests/testthat.R' failed.
> Complete output:
>    > library(testthat)
>    > library(BayesPostEst)
>    >
>    > test_check("BayesPostEst")
>    Error in library(R2jags) : there is no package called 'R2jags'
>    Calls: test_check ... source_dir -> lapply -> FUN -> eval -> eval ->
> library
>    Execution halted

There is a library(R2jags) in the tests, but I didn't want to flag that to not run if not interactive - I can go back and maybe mess with it? It's hard when my checks aren't reproducing their error. I'm also able to load the package *without* R2jags being on my local at all. Not sure if we should just add R2jags as a depends at this point to get past this issue or what.

**Comment by jayrobwilliams** [comment]
What platform is this error happening on?

**Comment by ShanaScogin** [comment]
I can't reproduce the error personally - but I think we shouldn't remove the examples just yet. I've made it to CRAN can't see it - I'll mess with it more now and update you

**Comment by ShanaScogin** [comment]
So, what seems to be happening is that R2jags *isn't* needed to load the package and use it, but it is needed to test (as in develop). Imo, this should be fine (and it has been in the past), but now it seems to be they are wanting it to where one has to have all the packages to test. I am not sure if the volunteer is testing on his local, but it passes on my local with R_CHECK_DEPENDS_ONLY_. I can reproduce his error if I run the check while I have removed the package. 

I have opinions on this, but now is not the time, but I'll figure something out and get it resubmitted today.

**Comment by ShanaScogin** [comment]
Added to depends and resubmitted. Opened issue #86 to clean up R2jags stuff in tests.

**Comment by ShanaScogin** [comment]
Sent back again. I think they want all packages used to best to be in depends, despite passing tests with DEPENDS=true variable set. I'll try to reproduce the errors they're getting and clean up.

**Comment by ShanaScogin** [comment]
Actually - I'd love to hear opinions others have at this point. Should I add all the tests we use in testing (like runjags) as dependencies, or is there something else I'm missing? I think the volunteer might be running this on local since it passes all automatic tests (and the test with DEPENDS on my local), so I don't think any type of skip on cran will help.

**Comment by ShanaScogin** [comment]
I just resubmitted (and cleaned up all my comments here!). Packages added to imports include: R2jags, runjags, rstanarm, rjags, MCMCpack, R2WinBUGS, brms. CRAN volunteer suggested just running code conditionally in the tests. If this is accepted, I can go back and change it for a small update.

**Comment by ShanaScogin** [comment]
Back up! The volunteer cut us some slack on the size - it's above 5MB again, so I'll work on that (and moving some of the imports to suggests with conditional code if possible) this week! Thanks all!
