### ISSUE TITLE
remove x*100 for plot.mcmcFD if ROPE is given

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#91]
Line 316 in https://github.com/ShanaScogin/BayesPostEst/blob/main/R/mcmcFD.R needs to go:

`ggplot2::scale_x_continuous(labels = function(x) x * 100) + `

because we already multiply x by 100 a few lines above

I'll take are of this ASAP

**Comment by ShanaScogin** [comment]
Sounds good - I was trying to fix some dependency issues last year, so I'll prioritize that after you're done so we can get that all updated together.

**Comment by jkarreth** [comment]
Great, @ShanaScogin ! I took a second look and now noticed that that line 

`ggplot2::scale_x_continuous(labels = function(x) x * 100) + `

needs to be removed in three lines, not just one ... 

I can either update this directly in the main branch right away or put it in dev, whichever you prefer :)

**Comment by ShanaScogin** [comment]
I guess dev - It looks like I left it a bit ahead of main last year, so if you change it, I'll go ahead and get everything caught up?

**Comment by jkarreth** [comment]
OK, changed in dev!
